[package]
name = "upcoming"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
calcard = "0.1.3"
gio = "0.21.0"
ical = "0.11.0"
jiff = "0.2.15"
tokio = { version = "1.46.1", features = ["macros", "rt", "rt-multi-thread"] }
zbus = "5.9.0"
